- name: Install forever package globally
  npm: name=forever global=yes state=present

- name: Install npm global packages
  npm: name={{item}} global=yes state=present
  with_items: npm.global_packages
  when: npm.global_packages

- name: Check list of Node.js apps running
  command: forever list
  register: forever_list
  changed_when: False

- stat: path=/vagrant/package.json
  register: vagpack

- name: Run npm install in /vagrant folder
  npm: path=/vagrant
  when: vagpack.stat.exists

- name: Start app in /vagrant/ folder
  command: forever start -c "npm start" /vagrant/
  when: "forever_list.stdout.find('/vagrant/') == -1"
  when: vagpack.stat.exists

- name: Run npm install in folders listed in apps.enabled
  npm: path={{ item }}
  with_items: apps.enabled
  when: apps is defined and apps.enabled is defined

- name: Start all enabled applications
  command: forever start -c "npm start" {{ item }}
  when: "forever_list.stdout.find('{{ item }}') == -1"
  with_items: apps.enabled
  when: apps is defined and apps.enabled is defined
